dist: xenial


sudo: false


services:
  - docker


language: python


python:
  - '3.5'
  - '3.6'
  - '3.7'


before_install:
  - git clone https://github.com/qcoumes/docker-wims-minimal.git wims_docker/
  - docker build -t wims-minimal wims_docker/
  - docker run -itd -p 7777:80 --name wims wims-minimal
  - docker container start wims
  - docker exec -it wims ./bin/apache-config
  - docker exec -it wims service apache2 restart
  - python3 manage.py makemigrations
  - python3 manage.py migrate


install:
  - pip install -U wheel setuptools
  - pip install tox-travis
  - pip install coveralls


script: tox
