dist: xenial


sudo: false


services: docker


language: python


python:
  - '3.5'
  - '3.6'
  - '3.7'


before_install:
  - git clone https://github.com/qcoumes/docker-api-minimal.git wims_docker/
  - docker build -t api-minimal wims_docker/
  - docker run -itd -p 7777:80 --name api api-minimal
  - docker container start api
  - docker exec -it api ./bin/apache-config
  - docker exec -it api service apache2 restart


install:
  - pip install -U wheel setuptools
  - pip install tox-travis
  - pip install codecov

script: tox

after_success: codecov
