name: Python package

on:
  push:
    branches:
      - master
      - dev
      - '*.*.*'
  pull_request:
    branches:
      - master
      - dev
      - '*.*.*'
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup the WIMS server
        run: |
          git clone https://github.com/qcoumes/docker-wims-minimal.git wims
          docker build -t wims-minimal wims/
          docker run -id -p 7777:80 --name wims wims-minimal
          docker container start wims
          docker exec -i wims ./bin/apache-config
          docker exec -i wims service apache2 restart

      - name: Install Tox and any other packages
        run: |
          pip install -U wheel setuptools
          pip install tox

      - name: Run Tox
        run: tox -e py

      - name: Upload coverage to Codecov
        if: matrix.python-version == 3.8
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
